CC=gcc
FLAGS=-pthread -O2
NOMBRE=Kernel_Simulator
make: Kernel_Simulator.c clock.c loader.c schedule_dispacher.c timer.c
	$(CC) $(FLAGS) -o $(NOMBRE) Kernel_Simulator.c clock.c loader.c schedule_dispacher.c timer.c